### ISSUE TITLE
Major Security Enhancement 

### ISSUE THREAD

**Issue by Librechain** [improvein/bitcoin-forge#12]
Happy to either work with you on this one or to just submit the pull request directly. 

Perhaps you can instantiate this as an additional module to what you were working on - but I wanted to request for the additino of 'BIP38' to the suite of Bitcoin configurations that you have because it would go perfectly with this app. 

## Explaining More 

Contrary to 'mnemonic' phrases (12/25 random human-readable words), BIP38 allows for a quasi-PAKE generation of one's Bitcoin address (stateless password generation type of flow). 

This link here explains this in much greater detail = https://patcito.github.io/mindwallet/mindwallet_0.1_SHA256_29f7c0bf801f352420a3d770af723503d770dc10e11e2753a0c266825936967e.html

Please let me know if any more information is necessary. 

Thank you (if interested I have a few additional requests / ideas beyond this one as well)

**Comment by diegogurpegui** [comment]
Hi !
First of all, every contribution or addition is welcome!

Regarding your suggestion for improvement, feel free to create a PR for review so we can take a look.

In what section or tool of Bitcoin Forge were you planning to add this? "Address"?
